import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pragmaticaMedium = localFont({
  src: "../fonts/PragmaticaExtendedBook.otf",
  variable: "--font-pragmatica-medium",
});

const pragmaticaBold = localFont({
  src: "../fonts/PragmaticaExtendedBold.otf",
  variable: "--font-pragmatica-bold",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pragmaticaMedium.variable} ${pragmaticaBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
